# -*- coding: utf-8 -*-
"""sistemaDeCadastro_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rV_PmJO5kx-p4y1CE-JwTKjkfDQpMofN
"""

#Importando bibliotecas
import json
import os

#Função para carregar o arquivo json
def carregarArquivo(nomeArquivo):
    if os.path.exists(nomeArquivo):
        with open(nomeArquivo, 'r') as arquivo:
            dataGeral = json.load(arquivo)
        return dataGeral
    else:
        return {}

#Função para salvar o arquivo json
def salvarArquivo(nome_arquivo, dados):
    with open(nome_arquivo, 'w') as arquivo:
        json.dump(dados, arquivo, indent=2)

#Adicionar usuário
def addUsuario(nomeArquivo, **usuario):
    if "Telefone" not in usuario:
        usuario["Telefone"] = "Não Informado"
    if "Endereço" not in usuario:
        usuario["Endereço"] = "Não Informado"

    dados = carregarArquivo(nomeArquivo)
    dados[len(dados)+1] = usuario
    salvarArquivo(nomeArquivo, dados)

#Excluir usuário
def excluirUsuario(nomeArquivo, *ids):
    dados = carregarArquivo(nomeArquivo)
    for id in ids:
        if id in dados:
            dados[str(id)]["Status"] = False
        else:
            print("Usuário não encontrado")

    salvarArquivo(nomeArquivo, dados)

#Editar informação de um usuário
def editUsuario(nomeArquivo, *ids):
    dados = carregarArquivo(nomeArquivo)
    for id in ids:
        if id in dados and dados[id]["Status"] == True:
            print(f"ID {id} - Usuário encontrado")
            opcao = int(input("Qual informação deseja alterar: 1-Nome 2-Telefone 3-Endereço: "))
            if opcao == 1:
                nome = input("Insira o nome: ")
                dados[id]["Nome"] = nome
            elif opcao == 2:
                telefone = input("Insira o telefone: ")
                dados[id]["Telefone"] = telefone
            elif opcao == 3:
                endereco = input("Insira o endereço: ")
                dados[id]["Endereço"] = endereco
            else:
                print("ERRO")
        else:
            print(f"Usuario com id {id} não encontrado.\n")

    salvarArquivo(nomeArquivo, dados)

#Exibir informações de um usuário
def exibirUsuarios(nomeArquivo,*ids):
    dados = carregarArquivo(nomeArquivo)
    for id in ids:
        if id in dados and dados[id]["Status"] == True:
            print(f'Nome: {dados[id]["Nome"]}')
            print(f'Telefone: {dados[id]["Telefone"]}')
            print(f'Endereço: {dados[id]["Endereço"]}\n')
        else:
            print(f"ID {id} - Usuário não encontrado\n")

def exibirTodosUsuarios(nomeArquivo):
    dados = carregarArquivo(nomeArquivo)
    for key,values in dados.items():
        if dados[key]["Status"] == True:
            print(f'ID: {key}')
            print(f'Nome: {dados[key]["Nome"]}')
            print(f'Telefone: {dados[key]["Telefone"]}')
            print(f'Endereço: {dados[key]["Endereço"]}\n')

def info(opcao):
    lista = []
    usuario = {}
    if opcao == 1:
        print("Digite as informações do usuário que será adicionado")
        usuario["Status"] = True
        usuario["Nome"] = input("Nome: ")
        usuario["Telefone"] = input("Telefone: ")
        usuario["Endereço"] = input("Endereço: ")
        return usuario
    else:
        while True:
            print("(S) para digitar um ID")
            print("(N) para voltar ao menu anterior")
            escolha = input("Digite a opção: ")
            if escolha in "Nn":
                break
            elif escolha in "Ss":
                lista.append(input("Digite um ID: "))
            else:
                print("Opção inálida. Tente novamente.")
        return(lista)

nomeArquivo = "/content/projetoModuloII.json"

while True:
    print("Boas vindas ao nosso sistema:")
    print("-"*30)
    print("1 - Inserir usuário")
    print("2 - Excluir usuário")
    print("3 - Atualizar usuário")
    print("4 - Informações de um usuário")
    print("5 - Informações de todos os usuários")
    print("6 - Sair")
    print("-"*30)

    while True:
        opcao = int(input("Digite uma opção: "))
        if opcao not in range(1,7):
            print("Opção inválida. Tente novamente")
        else:
            break
    if opcao == 1:
        usuario = info(opcao)
        addUsuario(nomeArquivo, **usuario)
    elif opcao == 2:
        ids = info(opcao)
        excluirUsuario(nomeArquivo,*ids)
    elif opcao == 3:
        ids = info(opcao)
        editUsuario(nomeArquivo,*ids)
    elif opcao == 4:
        ids = info(opcao)
        exibirUsuarios(nomeArquivo,*ids)
    elif opcao == 5:
        exibirTodosUsuarios(nomeArquivo)
    else:
        break

